---
title: "Resume"
---
EDUCATION
Columbia University                                                                                                                           September 2018 – May 2020
Mailman School of Public Health	
•	MS Biostatistics Theory and Methods

University of North Carolina at Chapel Hill 							August 2014 – May 2018
Gillings School of Global Public Health
•	BS Biostatistics Major, GPA 3.56
•	Mathematics and Chemistry Minor

EXPERIENCE
North Carolina Translational and Clinical Sciences Institute – Chapel Hill, NC			August 2017 – May 2018
A government funded institute that provides services to overcome barriers to translation research
Evaluation Research Assistant for Community Academic Resources for Engaged Scholarship (CARES)
•	Developed pre- and post-surveys using REDCap and Qualtrics for workshop/training/presentation evaluations
•	Monitored and evaluated the internal work activities of the CARES team; created monthly reports reflecting the work
•	Conducted literature reviews on methods of improving survey response rate and alternative non-survey evaluation
•	Reviewed evaluation plans and IRB protocols for CARES initiatives

Department of Psychology and Neuroscience at UNC-Chapel Hill			             January 2017 – May 2017
Psychological Sciences Research Assistant (under Neil Mulligan, PhD)
•	Studied factors affecting human memory and memory retrieval
•	Administered computerized tests to participants and observed/recorded responses
•	Performed data input and analysis of test results

Gillings School of Global Public Health at UNC-Chapel Hill				        September 2015 – May 2016
Environmental Sciences Volunteer Research Assistant (under Yvonne Yuen and Mark Sobsey, PhD)
•	Studied the effects of sunlight radiation on pathogens in water media in which people can become exposed
•	Used SAS to perform data analysis and create graphics representing data from sunlight radiation experiment results
•	Co-authored the graphs portion of a poster presented at the Water Resources Research Institute of the UNC System Annual Conference 2017

LEADERSHIP and COMMUNITY INVOLVEMENT
Global Brigades – Public Health Chapter							August 2014 – May 2018
A non-profit organization with a mission of empowering volunteers and under-resourced communities to resolve global health
President (August 2016 – Current), Travel Chair (August 2015 – May 2016)
•	Led a team of 12 students to Honduras to provide public health services
•	Constructed eco-stoves, latrines, and sanitation stations for families living in low sanitation communities
•	Planned and presented lessons on healthy lifestyle and sanitation for children in rural Honduran schools
•	Organized travel logistics and scheduling for team members

University of North Carolina at Chapel Hill Health Care 				         October 2016 – March 2017
Hospital Student Volunteer
•	Served as a liaison between patients and staff in the Emergency Department
•	Cared for the immediate comfort needs of patients; stocked patient products
•	Assisted nurses and ED staff with errands to different departments of the hospital

Luke Charity Clinic in Raleigh (February 27) – Translator 			    			   February 2016
•	Served as an English-Korean translator for patient-doctor communication

Criminal Justice Awareness and Action – Volunteer Mentor 				             January 2015 – May 2015
•	Mentored youth at the Durham Juvenile Detention Center on the importance of health, education, and moral justice

